import { InferGetStaticPropsType } from 'next'
import Head from 'next/head'
import { getHomePage } from '../lib/contentful/pages/home'

export async function getStaticProps() {
  return {
    props: { allCategories: await getHomePage() },
    revalidate: 60 * 60,
  }
}

export default function Home({
  allCategories,
}: InferGetStaticPropsType<typeof getStaticProps>) {
  console.log(allCategories)
  return (
    <div>
      <Head>
        <title>Transfer</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='m-8'>
        <h1 className='font-bold text-2xl mb-6'>TRANSFER</h1>
        {allCategories.map(({ engName }, idx) => (
          <p key={idx}>{engName}</p>
        ))}
      </div>
    </div>
  )
}
