import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Transfer</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <h1 className='font-bold text-2xl m-8'>TRANSFER</h1>
      <p className='m-8'>test</p>
    </div>
  )
}
